### PR TITLE
[TOMERGE] added start of documentation

### PR DESCRIPTION
**Pull request by LeonardBesseau**
Documentation as demanded in #12

#TODO ElementController, client need to send code instead of QR_id to addElement

### CODE REVIEW

**Comment by K-do** [comment]
I'd like to help

**Comment by LeonardBesseau** [comment]
We need to describe the API

**Comment by LeonardBesseau** [comment]
You can look at [this] (https://editor.swagger.io/)

**Comment by LeonardBesseau** [comment]
We could also add a document that describe how our server is structured

**Comment by K-do** [comment]
I'll add the documentation for my routes in the yaml file once the PR is accepted

**Comment by K-do** [comment]
EA schema updated

**Comment by LeonardBesseau** [comment]
API End point documented.
Will add link in README

**Comment by LeonardBesseau** [comment]
Added link in readMe. Feel free to close the issue when you want

**Review by K-do — APPROVED** [review]
Really good job!

**Comment by K-do** [comment]
Still don't know the utility of dir `openapi` ?

**Comment by K-do** [comment]
Need to resolve tests conflict before merge

**Comment by LeonardBesseau** [comment]
> Still don't know the utility of dir `openapi`... Seems that everything is made in dist.yaml

If yout want to modify the documentation with your editor and redoc. Otherwise you can directly edit dist.yaml

**Pull request merged**
