### PR TITLE
Add user functionality

### PR DESCRIPTION
**Pull request by LeonardBesseau**
Start of user management

### CODE REVIEW

**Comment by LeonardBesseau** [comment]
Might need a bit of polish on the presentation side but otherwise ok.
Still need to add a reload when an user is added/modified

**Comment by LeonardBesseau** [comment]
Auto reload when modification are done added

**Comment by LeonardBesseau** [comment]
All functionality are there. May need minimal change when we decide what to do with the active flag

**Review by K-do — APPROVED** [review]
Fixed aestehetic

**Pull request merged**
